const DEFAULT_AFFILIATE_LINKS = [
    { id: 1, status: 'fixed', priority: 1, title: 'Professional Logo Redesign', description: 'Transform your low-res logo into a high-quality vector file.', url: 'https://www.fiverr.com/categories/graphics-design/logo-design', price: 'From $15', signals: 'logo, brand, drawing, shape', icon: '🎨' },
    { id: 2, status: 'fixed', priority: 2, title: 'Expert Photoshop Editing', description: 'Remove backgrounds or retouch images for perfect clarity.', url: 'https://www.fiverr.com/categories/graphics-design/image-editing', price: 'Fast Delivery', signals: 'edit, photoshop, retouch, blur', icon: '✨' },
    { id: 3, status: 'dynamic', priority: 1, title: 'Native Language Translation', description: 'Get your text translated by human experts in 50+ languages.', url: 'https://www.fiverr.com/categories/writing-translation/translation', price: 'Top Rated', signals: 'translate, language, global, foreign', icon: '🌐' },
    { id: 4, status: 'dynamic', priority: 1, title: 'Proofreading & Editing', description: 'Fix grammar, syntax, and flow with professional editors.', url: 'https://www.fiverr.com/categories/writing-translation/proofreading-editing', price: 'From $5', signals: 'grammar, fix, flow, correction, spell', icon: '✍️' },
    { id: 5, status: 'dynamic', priority: 2, title: 'Content Writing Services', description: 'Hire writers to turn your notes into engaging articles or blogs.', url: 'https://www.fiverr.com/categories/writing-translation/articles-blog-posts', price: 'High Quality', signals: 'blog, article, write, story', icon: '📝' },
    { id: 6, status: 'dynamic', priority: 1, title: 'Manual Data Entry Pro', description: 'Need thousands of images converted? Outsource it to experts.', url: 'https://www.fiverr.com/categories/data/data-entry', price: 'Save Hours', signals: 'data, batch, volume, large, sheet', icon: '📊' },
    { id: 7, status: 'dynamic', priority: 1, title: 'Data Scraping & Mining', description: 'Transform extracted lists into organized Excel/CSV databases.', url: 'https://www.fiverr.com/categories/data/data-scraping', price: 'Certified', signals: 'list, database, csv, excel, scraper', icon: '🧠' },
    { id: 8, status: 'dynamic', priority: 2, title: 'Document Digitization', description: 'Convert handwritten scans into perfectly formatted Word docs.', url: 'https://www.fiverr.com/categories/data/data-processing', price: 'Starting $5', signals: 'handwrite, note, scan, paper', icon: '💾' },
    { id: 9, status: 'dynamic', priority: 1, title: 'Video Captioning / Subs', description: 'Add professional subtitles to your videos using your text.', url: 'https://www.fiverr.com/categories/video-animation/subtitles-captions', price: 'Engagement+', signals: 'video, movie, sub, caption, speech', icon: '🎬' },
    { id: 10, status: 'dynamic', priority: 1, title: 'Social Media Marketing', description: 'Promote your brand using your newly extracted content.', url: 'https://www.fiverr.com/categories/online-marketing/social-media-marketing', price: 'Grow Fast', signals: 'market, social, post, brand', icon: '📣' },
    { id: 11, status: 'dynamic', priority: 2, title: 'SEO Optimization Pro', description: 'Rank higher on Google with optimized text and descriptions.', url: 'https://www.fiverr.com/categories/online-marketing/seo', price: 'Rank #1', signals: 'seo, rank, keyword, search', icon: '📈' },
    { id: 12, status: 'dynamic', priority: 1, title: 'Custom OCR App Dev', description: 'Build your own private image-to-text tool for your company.', url: 'https://www.fiverr.com/categories/programming-tech/desktop-applications', price: 'Custom Dev', signals: 'build, develop, app, tool, software', icon: '💻' },
    { id: 13, status: 'dynamic', priority: 1, title: 'WordPress Specialist', description: 'Upload your extracted content directly to your WP site.', url: 'https://www.fiverr.com/categories/programming-tech/wordpress', price: 'Web Help', signals: 'website, wordpres, blog, site', icon: '🛠️' },
    { id: 14, status: 'dynamic', priority: 2, title: 'Cyber Security Review', description: 'Ensure your sensitive extracted documents remain secure.', url: 'https://www.fiverr.com/categories/programming-tech/cybersecurity', price: 'Safe & Secure', signals: 'secure, private, hack, safety', icon: '🔒' },
    { id: 15, status: 'default', priority: 1, title: 'Deep Sentiment Analysis', description: 'Understand the tone and mood behind your extracted text.', url: 'https://www.fiverr.com', price: 'Starting $5', signals: 'feel, mood, tone, sentiment', icon: '📊' },
    { id: 16, status: 'default', priority: 2, title: 'Book Formatting Pro', description: 'Turn your OCR text into a print-ready Amazon Kindle book.', url: 'https://www.fiverr.com', price: 'Best Seller', signals: 'book, kindle, print, author', icon: '📖' },
    { id: 17, status: 'default', priority: 3, title: 'Voiceover Recording', description: 'Let a professional voice actor read your extracted script.', url: 'https://www.fiverr.com', price: 'Studio Quality', signals: 'script, read, voice, audio', icon: '🗣️' },
    { id: 18, status: 'default', priority: 4, title: 'Business Plan Writing', description: 'Use your notes to create a winning startup business plan.', url: 'https://www.fiverr.com', price: 'Startup Ready', signals: 'business, plan, start, company', icon: '💼' },
    { id: 19, status: 'default', priority: 5, title: 'Transcription Specialist', description: 'Convert audio files related to your text into clean transcripts.', url: 'https://www.fiverr.com', price: '99% Accurate', signals: 'audio, hear, talk, record', icon: '📡' },
    { id: 20, status: 'default', priority: 6, title: 'Resume & CV Design', description: 'Update your professional profile using your extracted details.', url: 'https://www.fiverr.com', price: 'Get Hired', signals: 'job, resume, career, cv', icon: '👔' }
];

// For browser usage
if (typeof window !== 'undefined') {
    window.DEFAULT_AFFILIATE_LINKS = DEFAULT_AFFILIATE_LINKS;
}
